# Generated by Django 2.0.4 on 2018-04-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usertoken_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(max_length=500),
        ),
    ]
