# Generated by Django 2.0.4 on 2018-04-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='new category', max_length=255),
        ),
    ]
